apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      go-api: api
  template:
    metadata:
      labels:
        go-api: api
    spec:
      containers:
      - name: go-api
        image: ulicode/api:v1.1
        ports:
        - containerPort: 8080
        resources: 
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "150m"
---
apiVersion: v1
kind: Service
metadata:
  name: go-api
  namespace: default
spec:
  # type: LoadBalancer
  selector:
    go-api: api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      # type: NodePort 
      # nodePort: 30000
