apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: go-api-deployment 
  labels: 
    app: go-api 
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: go-api
  template:
    metadata:
      labels: 
        app: go-api
    spec: 
      containers:
      - name: go-api
        image: ulicode/api:v1
        ports:
        - containerPort: 8080